### ISSUE TITLE
Fix Hide Address Bar

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/reveal-js-presentations#3]
There is a toggle to Hide the Address Bar on Mobile. It's not working on the iPhone I tested it on. Perhaps it's an Android thing.

**Comment by mrjarbenne** [comment]
That toggle is located on this page if you are looking: 

https://sandbox.commons.hwdsb.on.ca/wp-admin/edit-tags.php?action=edit&taxonomy=presentation&tag_ID=351&post_type=slides

**Comment by r-a-y** [comment]
It appears this functionality wasn't implemented.

I've added this in the latest commits.  If you toggle the "Hide the address bar on mobile devices?" option for the presentation, this will hide the admin bar for the presentation.

The mobile check uses WP's own `wp_is_mobile()` function, so the mobile check is only as good as that function.

This is live on production for testing.

**Comment by mrjarbenne** [comment]
Works great. I think we can send a pull request on this one.

**Comment by r-a-y** [comment]
Curtiss says that the "Hide Address Bar on mobile" setting is related to reveal.js and not referring to the WP admin bar.

See https://github.com/cgrymala/reveal-js-presentations/pull/4#issuecomment-154406191

**Comment by mrjarbenne** [comment]
So we could potentially re-open #2 and add another toggle in settings, potentially implementing the auto hide idea from the plugin he mentioned.

I'm not seeing the address bar get hidden, but I'm content to utilize a browser full screen functionality to accomplish this.

**Comment by r-a-y** [comment]
Maybe talk things over with Curtiss before we start to implement something?

**Comment by mrjarbenne** [comment]
That makes good sense. I'll comment back on the pull request discussion.

**Comment by mrjarbenne** [comment]
@r-a-y can we revisit this? I'm hoping we can create a toggle that hides the adminbar on the presentation, regardless of platform (mobile or desktop) 

I believe most of the code is there, and just needs to be parsed out into its own toggle, leaving the current "Hide Address Bar" functionality alone.

I've tried in the meantime to hide the admin bar completely, using `show_admin_bar(false);`, but that only seems to work once you are logged in, foiling my plan to embed these presentations elsewhere to be viewed by non-logged in users. I think BP is overriding my hope to hide the admin bar on this site, due to a setting to show the adminbar to logged out users turned on in the Network Admin.

See http://www.hwdsb.on.ca/ancastersenior/announcements/ (ensure you aren't logged into the Commons) to see what I mean.

**Comment by mrjarbenne** [comment]
Actually. Crisis averted. The code needed a bit more love. This worked in the functions file of the theme I'm using to power the announcements. This can fall back in priority behind the other projects (video portal primarily).

```
/* Disable WordPress Admin Bar */
add_filter('show_admin_bar', '__return_false');
```
