### ISSUE TITLE
Slide Theme Background Broken on Some Themes

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/reveal-js-presentations#4]
The slide background takes on the background of the theme in some instances. 

For example: in Twenty Fifteen, and Mercury (A P2 child theme) the theme background trumps the background colour for the Reveal Slideshow theme

Screenshot of  a blank slide: 

![2015-10-27_10-43-50](https://cloud.githubusercontent.com/assets/480667/10923473/142e1dd8-824f-11e5-8558-b5ade0a0181b.png)

In Twenty Thirteen, the Reveal Slideshow theme is visible, so there must be something theme specific that is surfacing the theme background in some instances, but allowing the the Reveal Slideshow Background to show in others.

**Comment by r-a-y** [comment]
I've added a commit that removes the theme's stylesheet when on a presentation page.

This is available for testing on production.

**Comment by mrjarbenne** [comment]
Still seeing some inaccuracies. Perhaps theme CSS tags colliding with Reveal tags. 

Twenty Fifteen now working:

![image](https://cloud.githubusercontent.com/assets/480667/10970859/2af685cc-839f-11e5-909a-8ddd993d705a.png)

Mercury, using the same Reveal theme with Customizer colour selected:

![image](https://cloud.githubusercontent.com/assets/480667/10970888/54192978-839f-11e5-977e-5a184ccadffb.png)
![image](https://cloud.githubusercontent.com/assets/480667/10970889/542c17c2-839f-11e5-856f-8e1819e1ce34.png)

**Comment by r-a-y** [comment]
Thanks for the report.  I didn't account for parent themes!

I've added a fix to remove the parent theme's stylesheet as well when viewing a presentation.  This is live on production for testing.

**Comment by r-a-y** [comment]
Pull request was merged.  Closing!
