### ISSUE TITLE
Fatal Error in Logs

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/reveal-js-presentations#6]
[07-Dec-2016 03:22:31 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/reveal-js-presentations/classes/inc/preprocessors/scss.inc.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/reveal-js-presentations/classes/class-reveal-presentations.php on line 1590

**Comment by r-a-y** [comment]
How do you duplicate this bug?  (Edit: Looks like this occurs if JetPack isn't activated.)

It doesn't look like the `scss.inc.php` file is included in any of the directories.  You should open this on cgrymala's repo.

**Comment by mrjarbenne** [comment]
Sorry. Assigned and was working on an explanation, then got sidetracked reverting to a previous version of Jetpack. The plugin depends on Jetpack in order to work, and grabs the SCSS processors from the Jetpack CSS module. Jetpack just changed their CSS module "slightly" (139 commits: ugh) https://github.com/Automattic/jetpack/pull/5804 and seems to have borked this connection. It works in Jetpack 4.4.1 so I've reverted back for now. I'll post it out on cgrymala's repo. I'm not sure if he's still maintaining the project.

**Comment by r-a-y** [comment]
I've attempted a fix for this.  Let me know if it works with the latest JetPack version.

**Comment by mrjarbenne** [comment]
Cool. Checking now on the test server (I've broken the live environment enough times tonight).

**Comment by mrjarbenne** [comment]
I should have checked the live environement first (although now I'm set up for further testing over at this link: https://hwdsb.staging.boreal321.com/presentation/announcements/). That change you made seems to have broken it in the live environment (with the previous version of Jetpack 4.4.1). The plugin is running here if you want to be able to see it in the wild: https://508.commons.hwdsb.on.ca/presentation/announcements/

I've updated the test server to 4.4.2 to test over there.

**Comment by r-a-y** [comment]
Forgot to update production with the latest commit.

Looks like the 508 example is working again.  Dev environment is still broken, I'm looking into it.

**Comment by mrjarbenne** [comment]
Yes. Looks like we are close. That theme previously had a black background though, with white text. Is the CSS not getting processed properly perhaps? (that's some alliteration there)

**Comment by r-a-y** [comment]
I have no idea.  I'm not sure how the plugin works.  What happens if you disable the custom CSS from the presentation?

**Comment by mrjarbenne** [comment]
I just reverted your changes and it's working on production with the correct colour, with JP 4.4.1. I hadn't seen your separate Jetpack CSS Branch earlier. 

I don't have any custom CSS running on the presentation other than a small snippet to hide the Follow Blogs functionality from the bottom of the slide 

`#bpf-blogs-ftr a {
	display: none;
}`

We can wait and see what cgrymala thinks. It's getting late on this side of the country. I need to clock out.

**Comment by r-a-y** [comment]
I figured this out.

The current theme's CSS was taking precedence instead of using reveal.js' theme CSS.  I've fixed this in commit 09c07e7.  Dev server is running the latest `jetpack-css` commits.

**Comment by mrjarbenne** [comment]
Thanks for figuring this all out for us so quickly. Can I ask one more small favour? Can you create a pull request for the changes you made that sorted the issue for the cgrymala branch?

**Comment by r-a-y** [comment]
PR opened - https://github.com/cgrymala/reveal-js-presentations/issues/9
