### ISSUE TITLE
Limit slide content

### ISSUE THREAD

**Issue by r-a-y** [hwdsbcommons/reveal-js-presentations#9]
See https://github.com/hwdsbcommons/Limit-Post-Titles/issues/1

I think that issue should be posted here since we want to specifically limit post content for slides in this plugin.

I have an idea and that is to remove the post editor for slides and to replace it with the post excerpt metabox.  That way, we can easily add in a character limiter.

In order for this to work, we would need to add backward compatibility for those that used the post editor to add in slide content.

One thing I need to know is: Do slides currently have rich content?

If so, this idea would not work.  If we want a character limiter while also supporting rich content, that makes things trickier.

**Comment by r-a-y** [comment]
I tested this plugin and it works - https://wordpress.org/plugins/word-count-and-limit/

It's not intelligent or anything (no rich content omissions), but maybe we don't need it to be?

The good thing is it will work with the post editor, which will solve our problems here.

**Comment by mrjarbenne** [comment]
I didn't see this before updating the previous thread. https://github.com/hwdsbcommons/Limit-Post-Titles/issues/1

Users do have a tendancy to add rich content. Eventually I had hoped to add additional rich media capabilities to the plugin: https://github.com/hwdsbcommons/reveal-js-presentations/issues/7

**Comment by mrjarbenne** [comment]
Another argument for keeping the current editor is our use of the Unpublish plugin to allow users to auto-expire posts. I'm also looking at https://github.com/fusioneng/publishing-checklist to set requirements beyond the content character limits of this issue.

**Comment by mrjarbenne** [comment]
> I tested this plugin and it works - https://wordpress.org/plugins/word-count-and-limit/

> It's not intelligent or anything (no rich content omissions), but maybe we don't need it to be?

I'm not sure how I missed that one. I thought I found them all. If that one works, great. It doesn't need to be intelligent.

**Comment by r-a-y** [comment]
Let me know if the "Word Count and Limit" plugin will work for our needs.

**Comment by mrjarbenne** [comment]
Yes. This will work in concert with the other plugin that limits the count for the title field. 

![2017-09-11_21-00-38](https://user-images.githubusercontent.com/480667/30303210-57a0125a-9734-11e7-9922-f3a64ec08b4f.png)
